const express = require('express');
const http = require('http');
const socketIO = require('socket.io');
const mongoose = require('mongoose');
const cors = require('cors');
require('dotenv').config();
const app = express();
const server = http.createServer(app);
const io = socketIO(server, { cors: { origin: '*' } });
app.use(cors());
app.use(express.json());
mongoose.connect(process.env.MONGO_URI).then(() => console.log('MongoDB Connected!')).catch(err => console.log('DB Error:', err));
app.use('/api/owners', require('./routes/ownerRoutes'));
app.use('/api/players', require('./routes/playerRoutes'));
app.get('/', (req, res) => { res.json({ message: 'PSEL Auction Server Running!' }); });
const PORT = process.env.PORT || 5000;
server.listen(PORT, () => { console.log('Server running on port ' + PORT); });
